---
title: "Figures-non-interactive"
author: "mfpfox"
date: "2024-06-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(correlationfunnel)
library(tidyquant)
library(plotly)
library(tidyverse)
library(shiny)
```


```{r}
source('import-combined-lines-data.R')
```

```{r}

df[['SIFTprediction']] <- factor(df[['SIFTprediction']], levels = c(
  "tolerated_low_confidence",
  "tolerated",
  "deleterious",
  "deleterious_low_confidence"
))

df[['PolyPhenprediction']] <- factor(df[['PolyPhenprediction']], levels = c(
  "benign",
  "unknown",
  "possibly_damaging",
  "probably_damaging"
))

df[['VARIANT.CLASS']] <- factor(df[['VARIANT.CLASS']])
                                
df[['ZYG']] <- factor(df[['ZYG']])

df[['IND']] <- factor(df[['IND']])

df[['IMPACT']] <- factor(df[['IMPACT']])

summary(df)
```

```{r}
names(df)
```


```{r echo=TRUE}
df %>%
  dplyr::group_by(SIFTprediction, CLIN.SIG) %>%
  tally()

df %>%
  dplyr::group_by(PolyPhenprediction, CLIN.SIG) %>%
  tally()
```


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(readr)
library(scales)
library(ggpubr)
library(RColorBrewer)
library(tidyr)
library(plyr)
library(dplyr)
library(wesanderson)

```


```{r}
bp_colors = c("#FF0000", "#08519c")

normalized_dist_check <- ggplot(df, aes(x = MAX.AF, color=IND, fill = IND))

hist_all <- normalized_dist_check + 
  geom_histogram(position="identity", alpha=0.5)  + #bins=100, binwidth = 0.02 ,
  #geom_vline(data=summary_mean_median, aes(xintercept=Mean, color=Type), size=1,  linetype="dashed") + 
  #geom_vline(data=summary_mean_median, aes(xintercept=Median, color=Type), size=1, linetype="solid") + 
  theme_bw() +
  scale_fill_manual(values=bp_colors) +
  scale_color_manual(values=bp_colors) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_continuous(expand = c(0, 0)) + 
  #ylab("Count") +
 # xlab("Measurement (mmHg)") +
 # ggtitle("Distribution of systolic and diastolic measurements (n=87)") +
  theme(legend.position="right",
        plot.title = element_text(hjust=0.5), 
        axis.title.x = element_text(size=14, color="black", 
                                    margin=margin(t=15, b=5)),
        axis.title.y = element_text(size=14, color="black", margin=margin(t=0, r=15, b=0)), 
        axis.text=element_text(size=13,vjust=0.5, color="black", margin=margin(t=20, b=20))) +  facet_grid(IND ~ .)
hist_all

```


```{r}
bxplot <- ggboxplot(df, x = factor("VARIANT.CLASS"), y = "SIFTscore", 
                   # fill = ZYG, 
                    alpha=0.8, 
                    notch=FALSE) + 
    #stat_pvalue_manual(stat_table, label = stat_label) +
    #scale_fill_manual(values=colorname) + 
    #scale_y_continuous(n.breaks = 9, limits=yrange) +
    theme_bw() + 
    # labs(x=xname,
    #      y= ylabel,
    #         title = titlename,
    #      subtitle = subname,
    #      caption = capname) +  
    theme(panel.grid.minor = element_blank()) +
    theme(legend.position='right') + 
    theme(
            axis.title.x = element_text(size=14, color="black", margin=margin(t=15, b=5)),
            axis.title.y = element_text(size=14, color="black", margin=margin(t=0, r=15, b=0)), 
            axis.text=element_text(size=12, color="black", margin=margin(t=20, b=20)))  
bxplot
```

